# Generated by Django 4.1.5 on 2023-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='created1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50)),
                ('password1', models.IntegerField(default='', max_length=20)),
                ('Fname', models.CharField(default='', max_length=50)),
                ('Lname', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('pass1', models.IntegerField(default='', max_length=20)),
                ('mobile', models.IntegerField(default='', max_length=20)),
                ('branch', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
